version: '3.1'

services:

  drupal:
    image: bitsamericas/selfcare
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
      - ./logs:/var/log/nginx/
    depends_on:
      - mysql
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=host.docker.internal

  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=1073741824
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tigo_selfcare
    volumes:
      - ./mysql_data:/var/lib/mysql
